In [1]:
#slicing in numpy
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[0:3])

[10 20 30]


In [2]:
#slicing in numpy
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[3:6])

[40 50 60]


In [3]:
#slicing in numpy with no end index
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[3:])

[40 50 60 70 80]


In [5]:
#slicing in numpy with no start index
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[:5])

[10 20 30 40 50]


In [6]:
# -ve slicing in numpy 
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[-5:-1])

[40 50 60 70]


In [8]:
# -ve and +ve slicing in numpy 
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[1:-1])

[20 30 40 50 60 70]


In [9]:
#slicing in numpy with step
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[0:6:2])

[10 30 50]


In [10]:
#slicing in numpy with step
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[::])

[10 20 30 40 50 60 70 80]


In [11]:
#slicing in numpy with step
import numpy as np

i = np.array([10,20,30,40,50,60,70,80])
print(i[::2])

[10 30 50 70]


In [12]:
# slicing with 2D arrays
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
print(i[1,0:3])

[60 70 80]


In [13]:
# slicing with 2D arrays
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
print(i[0,1:4])

[20 30 40]


In [14]:
# slicing with 2D arrays
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55]
])
print(i[2,1:4])

[22 33 44]


In [15]:
# slicing with 2D arrays
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55]
])
print(i[0:2,1])

[20 70]


In [17]:
# slicing with 2D arrays
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55],
    [1,2,3,4,5]
])
print(i[0:3,4])

[ 50 100  55]


In [18]:
# slicing with 2D arrays
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55],
    [1,2,3,4,5]
])
print(i[0:3,0:4])

[[10 20 30 40]
 [60 70 80 90]
 [11 22 33 44]]


In [20]:
# slicing with 2D arrays -ve indexing
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100],
    [11,22,33,44,55],
    [1,2,3,4,5]
])
print(i[0:3,-3:-1])

[[30 40]
 [80 90]
 [33 44]]


In [21]:
# data type in numpy
import numpy as np

np.array([10,20,30,40,50])
print(i.dtype)

int32


In [27]:
# data type in numpy
import numpy as np

i = np.array([10.10,20.20,30.30])
i1 = i.astype('i')
print(i1)
print(i1.dtype)
print(i)

[10 20 30]
int32
[10.1 20.2 30.3]


In [28]:
# data type in numpy
import numpy as np

i = np.array([10,20,30])
i1 = i.astype('f')
print(i1)
print(i1.dtype)


[10. 20. 30.]
float32


In [29]:
# data type in numpy
import numpy as np

i = np.array([10.10,20.20,30.30])
i1 = i.astype(int)
print(i1)
print(i1.dtype)


[10 20 30]
int32


In [30]:
# data type in numpy
import numpy as np

i = np.array([10.10,0,20,35.2,30,0,3])
i1 = i.astype(bool)
print(i1)
print(i1.dtype)

[ True False  True  True  True False  True]
bool
