In [9]:
# Simple Numpy program
import numpy

i = numpy.array([10,20,30,40])
print(i)

[10 20 30 40]


In [10]:
# Simple Numpy program
import numpy as np

i = np.array([10,20,30,40])
print(i)

[10 20 30 40]


In [5]:
# Check Numpy version
import numpy as np

print(np.__version__)

1.20.3


In [7]:
# type() function in Numpy
import numpy as np

i = np.array([10,20,30,40])
print(i)
print(type(i))


[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
# Numpy Example with Tuple
import numpy as np

i = np.array((10,20,30,40))
print(i)

[10 20 30 40]


In [11]:
# 0-D Dimention array in Numpy
import numpy as np

i = np.array(10)
print(i)

10


In [12]:
# 1-D Dimention array in Numpy
import numpy as np

i = np.array([10,20,30,40,50,60])
print(i)

[10 20 30 40 50 60]


In [15]:
# 2-D Dimention array in Numpy
import numpy as np

i = np.array([[10,20,30,40],
              [50,60,70,80]])
print(i)

[[10 20 30 40]
 [50 60 70 80]]


In [16]:
# 3-D Dimention array in Numpy
import numpy as np

i = np.array([
    [[10,20,30,40],[50,60,70,80]],
    [[50,60,70,80],[10,20,30,40]]
])
print(i)

[[[10 20 30 40]
  [50 60 70 80]]

 [[50 60 70 80]
  [10 20 30 40]]]


In [17]:
# Check the type of Dimention
import numpy as np

i = np.array(10)
j = np.array([10,20,30,40,50,60])
k = np.array([[10,20,30,40],
              [50,60,70,80]])
l = np.array([
    [[10,20,30,40],[50,60,70,80]],
    [[50,60,70,80],[10,20,30,40]]
])

print(i.ndim)
print(j.ndim)
print(k.ndim)
print(l.ndim)

0
1
2
3


In [19]:
# ndmin argument in Numpy.
import numpy as np

i = np.array([10,20,30,40,50,60], ndmin=5)
print(i)
print(i.ndim)

[[[[[10 20 30 40 50 60]]]]]
5


In [20]:
# Access elements in Numpy
import numpy as np

i = np.array([10,20,30,40,50,60])
print(i[0])

10


In [22]:
# Access elements in Numpy
import numpy as np

i = np.array([[10,20,30,40],
              [50,60,70,80]])
print(i[1,1])
print(i[0,1])

60
20


In [26]:
# Access elements in Numpy
import numpy as np

i = np.array([
    [[10,20,30,40],[50,60,70,80]], # 0 - 0 1 - 0 1 2 
    [[50,60,70,80],[10,20,30,40]]  # 0 - 0 1 - 0 1 2 
])
print(i[0,1,2])
print(i[1,1,2])
print(i[1,1,-1])
print(i[1,-2,-1])

70
30
40
80


In [27]:
# Access elements in Numpy
import numpy as np

i = np.array([10,20,30,40,50,60])
print(i[-1])

60
